// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: binder_driver_data_link.proto
#ifndef GRPC_binder_5fdriver_5fdata_5flink_2eproto__INCLUDED
#define GRPC_binder_5fdriver_5fdata_5flink_2eproto__INCLUDED

#include "binder_driver_data_link.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace grpc {
class CompletionQueue;
class Channel;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc

namespace BinderDriverDataLink {

// The greeting service definition.
class BinderDriverService final {
 public:
  static constexpr char const* service_full_name() {
    return "BinderDriverDataLink.BinderDriverService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::BinderDriverDataLink::MessageFromClient, ::BinderDriverDataLink::MessageFromServer>> BidirectionalStreamMessages(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::BinderDriverDataLink::MessageFromClient, ::BinderDriverDataLink::MessageFromServer>>(BidirectionalStreamMessagesRaw(context));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::BinderDriverDataLink::MessageFromClient, ::BinderDriverDataLink::MessageFromServer>> AsyncBidirectionalStreamMessages(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::BinderDriverDataLink::MessageFromClient, ::BinderDriverDataLink::MessageFromServer>>(AsyncBidirectionalStreamMessagesRaw(context, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::BinderDriverDataLink::MessageFromClient, ::BinderDriverDataLink::MessageFromServer>> PrepareAsyncBidirectionalStreamMessages(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::BinderDriverDataLink::MessageFromClient, ::BinderDriverDataLink::MessageFromServer>>(PrepareAsyncBidirectionalStreamMessagesRaw(context, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
    };
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientReaderWriterInterface< ::BinderDriverDataLink::MessageFromClient, ::BinderDriverDataLink::MessageFromServer>* BidirectionalStreamMessagesRaw(::grpc::ClientContext* context) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::BinderDriverDataLink::MessageFromClient, ::BinderDriverDataLink::MessageFromServer>* AsyncBidirectionalStreamMessagesRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::BinderDriverDataLink::MessageFromClient, ::BinderDriverDataLink::MessageFromServer>* PrepareAsyncBidirectionalStreamMessagesRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    std::unique_ptr< ::grpc::ClientReaderWriter< ::BinderDriverDataLink::MessageFromClient, ::BinderDriverDataLink::MessageFromServer>> BidirectionalStreamMessages(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriter< ::BinderDriverDataLink::MessageFromClient, ::BinderDriverDataLink::MessageFromServer>>(BidirectionalStreamMessagesRaw(context));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::BinderDriverDataLink::MessageFromClient, ::BinderDriverDataLink::MessageFromServer>> AsyncBidirectionalStreamMessages(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::BinderDriverDataLink::MessageFromClient, ::BinderDriverDataLink::MessageFromServer>>(AsyncBidirectionalStreamMessagesRaw(context, cq, tag));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::BinderDriverDataLink::MessageFromClient, ::BinderDriverDataLink::MessageFromServer>> PrepareAsyncBidirectionalStreamMessages(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::BinderDriverDataLink::MessageFromClient, ::BinderDriverDataLink::MessageFromServer>>(PrepareAsyncBidirectionalStreamMessagesRaw(context, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientReaderWriter< ::BinderDriverDataLink::MessageFromClient, ::BinderDriverDataLink::MessageFromServer>* BidirectionalStreamMessagesRaw(::grpc::ClientContext* context) override;
    ::grpc::ClientAsyncReaderWriter< ::BinderDriverDataLink::MessageFromClient, ::BinderDriverDataLink::MessageFromServer>* AsyncBidirectionalStreamMessagesRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReaderWriter< ::BinderDriverDataLink::MessageFromClient, ::BinderDriverDataLink::MessageFromServer>* PrepareAsyncBidirectionalStreamMessagesRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_BidirectionalStreamMessages_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status BidirectionalStreamMessages(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::BinderDriverDataLink::MessageFromServer, ::BinderDriverDataLink::MessageFromClient>* stream);
  };
  template <class BaseClass>
  class WithAsyncMethod_BidirectionalStreamMessages : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_BidirectionalStreamMessages() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_BidirectionalStreamMessages() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status BidirectionalStreamMessages(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::BinderDriverDataLink::MessageFromServer, ::BinderDriverDataLink::MessageFromClient>* stream)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestBidirectionalStreamMessages(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::BinderDriverDataLink::MessageFromServer, ::BinderDriverDataLink::MessageFromClient>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(0, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_BidirectionalStreamMessages<Service > AsyncService;
  template <class BaseClass>
  class WithGenericMethod_BidirectionalStreamMessages : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_BidirectionalStreamMessages() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_BidirectionalStreamMessages() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status BidirectionalStreamMessages(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::BinderDriverDataLink::MessageFromServer, ::BinderDriverDataLink::MessageFromClient>* stream)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_BidirectionalStreamMessages : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithRawMethod_BidirectionalStreamMessages() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_BidirectionalStreamMessages() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status BidirectionalStreamMessages(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::BinderDriverDataLink::MessageFromServer, ::BinderDriverDataLink::MessageFromClient>* stream)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestBidirectionalStreamMessages(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(0, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  typedef Service StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef Service StreamedService;
};

}  // namespace BinderDriverDataLink


#endif  // GRPC_binder_5fdriver_5fdata_5flink_2eproto__INCLUDED
