// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: binder_driver_data_link.proto

#include "binder_driver_data_link.pb.h"

#include <algorithm>
#include <cstdint>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
#include "google/protobuf/generated_message_tctable_impl.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace BinderDriverDataLink {

inline constexpr MessageFromServer::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : msg_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        buffer_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        id_{::uint64_t{0u}},
        type_{0u},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR MessageFromServer::MessageFromServer(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct MessageFromServerDefaultTypeInternal {
  PROTOBUF_CONSTEXPR MessageFromServerDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~MessageFromServerDefaultTypeInternal() {}
  union {  // NOLINT(misc-non-private-member-variables-in-classes)
    MessageFromServer _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 MessageFromServerDefaultTypeInternal _MessageFromServer_default_instance_;

inline constexpr MessageFromClient::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : msg_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        buffer_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        id_{::uint64_t{0u}},
        type_{0u},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR MessageFromClient::MessageFromClient(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct MessageFromClientDefaultTypeInternal {
  PROTOBUF_CONSTEXPR MessageFromClientDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~MessageFromClientDefaultTypeInternal() {}
  union {  // NOLINT(misc-non-private-member-variables-in-classes)
    MessageFromClient _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 MessageFromClientDefaultTypeInternal _MessageFromClient_default_instance_;
}  // namespace BinderDriverDataLink
static ::_pb::Metadata file_level_metadata_binder_5fdriver_5fdata_5flink_2eproto[2];
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_binder_5fdriver_5fdata_5flink_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_binder_5fdriver_5fdata_5flink_2eproto = nullptr;
const ::uint32_t TableStruct_binder_5fdriver_5fdata_5flink_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(
    protodesc_cold) = {
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::BinderDriverDataLink::MessageFromServer, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::BinderDriverDataLink::MessageFromServer, _impl_.id_),
    PROTOBUF_FIELD_OFFSET(::BinderDriverDataLink::MessageFromServer, _impl_.type_),
    PROTOBUF_FIELD_OFFSET(::BinderDriverDataLink::MessageFromServer, _impl_.msg_),
    PROTOBUF_FIELD_OFFSET(::BinderDriverDataLink::MessageFromServer, _impl_.buffer_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::BinderDriverDataLink::MessageFromClient, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::BinderDriverDataLink::MessageFromClient, _impl_.id_),
    PROTOBUF_FIELD_OFFSET(::BinderDriverDataLink::MessageFromClient, _impl_.type_),
    PROTOBUF_FIELD_OFFSET(::BinderDriverDataLink::MessageFromClient, _impl_.msg_),
    PROTOBUF_FIELD_OFFSET(::BinderDriverDataLink::MessageFromClient, _impl_.buffer_),
};

static const ::_pbi::MigrationSchema
    schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::BinderDriverDataLink::MessageFromServer)},
        {12, -1, -1, sizeof(::BinderDriverDataLink::MessageFromClient)},
};

static const ::_pb::Message* const file_default_instances[] = {
    &::BinderDriverDataLink::_MessageFromServer_default_instance_._instance,
    &::BinderDriverDataLink::_MessageFromClient_default_instance_._instance,
};
const char descriptor_table_protodef_binder_5fdriver_5fdata_5flink_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
    "\n\035binder_driver_data_link.proto\022\024BinderD"
    "riverDataLink\"J\n\021MessageFromServer\022\n\n\002id"
    "\030\001 \001(\004\022\014\n\004type\030\002 \001(\r\022\013\n\003msg\030\003 \001(\t\022\016\n\006buf"
    "fer\030\004 \001(\014\"J\n\021MessageFromClient\022\n\n\002id\030\001 \001"
    "(\004\022\014\n\004type\030\002 \001(\r\022\013\n\003msg\030\003 \001(\t\022\016\n\006buffer\030"
    "\004 \001(\0142\214\001\n\023BinderDriverService\022u\n\033Bidirec"
    "tionalStreamMessages\022\'.BinderDriverDataL"
    "ink.MessageFromClient\032\'.BinderDriverData"
    "Link.MessageFromServer\"\000(\0010\001B5\n\025io.grpc."
    "binder.driverB\024BinderDriverDataLinkP\001\242\002\003"
    "BNDb\006proto3"
};
static ::absl::once_flag descriptor_table_binder_5fdriver_5fdata_5flink_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_binder_5fdriver_5fdata_5flink_2eproto = {
    false,
    false,
    411,
    descriptor_table_protodef_binder_5fdriver_5fdata_5flink_2eproto,
    "binder_driver_data_link.proto",
    &descriptor_table_binder_5fdriver_5fdata_5flink_2eproto_once,
    nullptr,
    0,
    2,
    schemas,
    file_default_instances,
    TableStruct_binder_5fdriver_5fdata_5flink_2eproto::offsets,
    file_level_metadata_binder_5fdriver_5fdata_5flink_2eproto,
    file_level_enum_descriptors_binder_5fdriver_5fdata_5flink_2eproto,
    file_level_service_descriptors_binder_5fdriver_5fdata_5flink_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_binder_5fdriver_5fdata_5flink_2eproto_getter() {
  return &descriptor_table_binder_5fdriver_5fdata_5flink_2eproto;
}
// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_binder_5fdriver_5fdata_5flink_2eproto(&descriptor_table_binder_5fdriver_5fdata_5flink_2eproto);
namespace BinderDriverDataLink {
// ===================================================================

class MessageFromServer::_Internal {
 public:
};

MessageFromServer::MessageFromServer(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:BinderDriverDataLink.MessageFromServer)
}
inline PROTOBUF_NDEBUG_INLINE MessageFromServer::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : msg_(arena, from.msg_),
        buffer_(arena, from.buffer_),
        _cached_size_{0} {}

MessageFromServer::MessageFromServer(
    ::google::protobuf::Arena* arena,
    const MessageFromServer& from)
    : ::google::protobuf::Message(arena) {
  MessageFromServer* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, id_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, id_),
           offsetof(Impl_, type_) -
               offsetof(Impl_, id_) +
               sizeof(Impl_::type_));

  // @@protoc_insertion_point(copy_constructor:BinderDriverDataLink.MessageFromServer)
}
inline PROTOBUF_NDEBUG_INLINE MessageFromServer::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : msg_(arena),
        buffer_(arena),
        _cached_size_{0} {}

inline void MessageFromServer::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, id_),
           0,
           offsetof(Impl_, type_) -
               offsetof(Impl_, id_) +
               sizeof(Impl_::type_));
}
MessageFromServer::~MessageFromServer() {
  // @@protoc_insertion_point(destructor:BinderDriverDataLink.MessageFromServer)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void MessageFromServer::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.msg_.Destroy();
  _impl_.buffer_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void MessageFromServer::Clear() {
// @@protoc_insertion_point(message_clear_start:BinderDriverDataLink.MessageFromServer)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.msg_.ClearToEmpty();
  _impl_.buffer_.ClearToEmpty();
  ::memset(&_impl_.id_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.type_) -
      reinterpret_cast<char*>(&_impl_.id_)) + sizeof(_impl_.type_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* MessageFromServer::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 4, 0, 50, 2> MessageFromServer::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    4, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967280,  // skipmap
    offsetof(decltype(_table_), field_entries),
    4,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_MessageFromServer_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // bytes buffer = 4;
    {::_pbi::TcParser::FastBS1,
     {34, 63, 0, PROTOBUF_FIELD_OFFSET(MessageFromServer, _impl_.buffer_)}},
    // uint64 id = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(MessageFromServer, _impl_.id_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(MessageFromServer, _impl_.id_)}},
    // uint32 type = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(MessageFromServer, _impl_.type_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(MessageFromServer, _impl_.type_)}},
    // string msg = 3;
    {::_pbi::TcParser::FastUS1,
     {26, 63, 0, PROTOBUF_FIELD_OFFSET(MessageFromServer, _impl_.msg_)}},
  }}, {{
    65535, 65535
  }}, {{
    // uint64 id = 1;
    {PROTOBUF_FIELD_OFFSET(MessageFromServer, _impl_.id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt64)},
    // uint32 type = 2;
    {PROTOBUF_FIELD_OFFSET(MessageFromServer, _impl_.type_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt32)},
    // string msg = 3;
    {PROTOBUF_FIELD_OFFSET(MessageFromServer, _impl_.msg_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // bytes buffer = 4;
    {PROTOBUF_FIELD_OFFSET(MessageFromServer, _impl_.buffer_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBytes | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\46\0\0\3\0\0\0\0"
    "BinderDriverDataLink.MessageFromServer"
    "msg"
  }},
};

::uint8_t* MessageFromServer::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:BinderDriverDataLink.MessageFromServer)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // uint64 id = 1;
  if (this->_internal_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
        1, this->_internal_id(), target);
  }

  // uint32 type = 2;
  if (this->_internal_type() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        2, this->_internal_type(), target);
  }

  // string msg = 3;
  if (!this->_internal_msg().empty()) {
    const std::string& _s = this->_internal_msg();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "BinderDriverDataLink.MessageFromServer.msg");
    target = stream->WriteStringMaybeAliased(3, _s, target);
  }

  // bytes buffer = 4;
  if (!this->_internal_buffer().empty()) {
    const std::string& _s = this->_internal_buffer();
    target = stream->WriteBytesMaybeAliased(4, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:BinderDriverDataLink.MessageFromServer)
  return target;
}

::size_t MessageFromServer::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:BinderDriverDataLink.MessageFromServer)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string msg = 3;
  if (!this->_internal_msg().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_msg());
  }

  // bytes buffer = 4;
  if (!this->_internal_buffer().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                    this->_internal_buffer());
  }

  // uint64 id = 1;
  if (this->_internal_id() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
        this->_internal_id());
  }

  // uint32 type = 2;
  if (this->_internal_type() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
        this->_internal_type());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData MessageFromServer::_class_data_ = {
    MessageFromServer::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* MessageFromServer::GetClassData() const {
  return &_class_data_;
}

void MessageFromServer::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<MessageFromServer*>(&to_msg);
  auto& from = static_cast<const MessageFromServer&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:BinderDriverDataLink.MessageFromServer)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_msg().empty()) {
    _this->_internal_set_msg(from._internal_msg());
  }
  if (!from._internal_buffer().empty()) {
    _this->_internal_set_buffer(from._internal_buffer());
  }
  if (from._internal_id() != 0) {
    _this->_internal_set_id(from._internal_id());
  }
  if (from._internal_type() != 0) {
    _this->_internal_set_type(from._internal_type());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void MessageFromServer::CopyFrom(const MessageFromServer& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:BinderDriverDataLink.MessageFromServer)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool MessageFromServer::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* MessageFromServer::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void MessageFromServer::InternalSwap(MessageFromServer* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.msg_, &other->_impl_.msg_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.buffer_, &other->_impl_.buffer_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(MessageFromServer, _impl_.type_)
      + sizeof(MessageFromServer::_impl_.type_)  // NOLINT
      - PROTOBUF_FIELD_OFFSET(MessageFromServer, _impl_.id_)>(
          reinterpret_cast<char*>(&_impl_.id_),
          reinterpret_cast<char*>(&other->_impl_.id_));
}

::google::protobuf::Metadata MessageFromServer::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_binder_5fdriver_5fdata_5flink_2eproto_getter, &descriptor_table_binder_5fdriver_5fdata_5flink_2eproto_once,
      file_level_metadata_binder_5fdriver_5fdata_5flink_2eproto[0]);
}
// ===================================================================

class MessageFromClient::_Internal {
 public:
};

MessageFromClient::MessageFromClient(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:BinderDriverDataLink.MessageFromClient)
}
inline PROTOBUF_NDEBUG_INLINE MessageFromClient::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : msg_(arena, from.msg_),
        buffer_(arena, from.buffer_),
        _cached_size_{0} {}

MessageFromClient::MessageFromClient(
    ::google::protobuf::Arena* arena,
    const MessageFromClient& from)
    : ::google::protobuf::Message(arena) {
  MessageFromClient* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, id_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, id_),
           offsetof(Impl_, type_) -
               offsetof(Impl_, id_) +
               sizeof(Impl_::type_));

  // @@protoc_insertion_point(copy_constructor:BinderDriverDataLink.MessageFromClient)
}
inline PROTOBUF_NDEBUG_INLINE MessageFromClient::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : msg_(arena),
        buffer_(arena),
        _cached_size_{0} {}

inline void MessageFromClient::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, id_),
           0,
           offsetof(Impl_, type_) -
               offsetof(Impl_, id_) +
               sizeof(Impl_::type_));
}
MessageFromClient::~MessageFromClient() {
  // @@protoc_insertion_point(destructor:BinderDriverDataLink.MessageFromClient)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void MessageFromClient::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.msg_.Destroy();
  _impl_.buffer_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void MessageFromClient::Clear() {
// @@protoc_insertion_point(message_clear_start:BinderDriverDataLink.MessageFromClient)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.msg_.ClearToEmpty();
  _impl_.buffer_.ClearToEmpty();
  ::memset(&_impl_.id_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.type_) -
      reinterpret_cast<char*>(&_impl_.id_)) + sizeof(_impl_.type_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* MessageFromClient::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 4, 0, 50, 2> MessageFromClient::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    4, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967280,  // skipmap
    offsetof(decltype(_table_), field_entries),
    4,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_MessageFromClient_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // bytes buffer = 4;
    {::_pbi::TcParser::FastBS1,
     {34, 63, 0, PROTOBUF_FIELD_OFFSET(MessageFromClient, _impl_.buffer_)}},
    // uint64 id = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(MessageFromClient, _impl_.id_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(MessageFromClient, _impl_.id_)}},
    // uint32 type = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(MessageFromClient, _impl_.type_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(MessageFromClient, _impl_.type_)}},
    // string msg = 3;
    {::_pbi::TcParser::FastUS1,
     {26, 63, 0, PROTOBUF_FIELD_OFFSET(MessageFromClient, _impl_.msg_)}},
  }}, {{
    65535, 65535
  }}, {{
    // uint64 id = 1;
    {PROTOBUF_FIELD_OFFSET(MessageFromClient, _impl_.id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt64)},
    // uint32 type = 2;
    {PROTOBUF_FIELD_OFFSET(MessageFromClient, _impl_.type_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt32)},
    // string msg = 3;
    {PROTOBUF_FIELD_OFFSET(MessageFromClient, _impl_.msg_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // bytes buffer = 4;
    {PROTOBUF_FIELD_OFFSET(MessageFromClient, _impl_.buffer_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBytes | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\46\0\0\3\0\0\0\0"
    "BinderDriverDataLink.MessageFromClient"
    "msg"
  }},
};

::uint8_t* MessageFromClient::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:BinderDriverDataLink.MessageFromClient)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // uint64 id = 1;
  if (this->_internal_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
        1, this->_internal_id(), target);
  }

  // uint32 type = 2;
  if (this->_internal_type() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        2, this->_internal_type(), target);
  }

  // string msg = 3;
  if (!this->_internal_msg().empty()) {
    const std::string& _s = this->_internal_msg();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "BinderDriverDataLink.MessageFromClient.msg");
    target = stream->WriteStringMaybeAliased(3, _s, target);
  }

  // bytes buffer = 4;
  if (!this->_internal_buffer().empty()) {
    const std::string& _s = this->_internal_buffer();
    target = stream->WriteBytesMaybeAliased(4, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:BinderDriverDataLink.MessageFromClient)
  return target;
}

::size_t MessageFromClient::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:BinderDriverDataLink.MessageFromClient)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string msg = 3;
  if (!this->_internal_msg().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_msg());
  }

  // bytes buffer = 4;
  if (!this->_internal_buffer().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                    this->_internal_buffer());
  }

  // uint64 id = 1;
  if (this->_internal_id() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
        this->_internal_id());
  }

  // uint32 type = 2;
  if (this->_internal_type() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
        this->_internal_type());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData MessageFromClient::_class_data_ = {
    MessageFromClient::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* MessageFromClient::GetClassData() const {
  return &_class_data_;
}

void MessageFromClient::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<MessageFromClient*>(&to_msg);
  auto& from = static_cast<const MessageFromClient&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:BinderDriverDataLink.MessageFromClient)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_msg().empty()) {
    _this->_internal_set_msg(from._internal_msg());
  }
  if (!from._internal_buffer().empty()) {
    _this->_internal_set_buffer(from._internal_buffer());
  }
  if (from._internal_id() != 0) {
    _this->_internal_set_id(from._internal_id());
  }
  if (from._internal_type() != 0) {
    _this->_internal_set_type(from._internal_type());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void MessageFromClient::CopyFrom(const MessageFromClient& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:BinderDriverDataLink.MessageFromClient)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool MessageFromClient::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* MessageFromClient::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void MessageFromClient::InternalSwap(MessageFromClient* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.msg_, &other->_impl_.msg_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.buffer_, &other->_impl_.buffer_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(MessageFromClient, _impl_.type_)
      + sizeof(MessageFromClient::_impl_.type_)  // NOLINT
      - PROTOBUF_FIELD_OFFSET(MessageFromClient, _impl_.id_)>(
          reinterpret_cast<char*>(&_impl_.id_),
          reinterpret_cast<char*>(&other->_impl_.id_));
}

::google::protobuf::Metadata MessageFromClient::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_binder_5fdriver_5fdata_5flink_2eproto_getter, &descriptor_table_binder_5fdriver_5fdata_5flink_2eproto_once,
      file_level_metadata_binder_5fdriver_5fdata_5flink_2eproto[1]);
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace BinderDriverDataLink
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
